### ISSUE TITLE
plugin does not appear in plugins list

### ISSUE THREAD

**Issue by kgnfth** [darron1217/strapi-plugin-video-thumbnail#1]
using Strapi v3.4.6 
installed "strapi-plugin-video-thumbnail": "^0.1.2",

**Comment by darron1217** [comment]
I'm currently using Strapi `v3.4.4` and it works well on my version.
Anyway, did you run `yarn build` after installation?

**Comment by kgnfth** [comment]
yes i can see it now in the menu but how does the plugin work
does it generate thumbnail after you upload video

**Comment by darron1217** [comment]
This plugin uses `beforeCreate` database lifecycle hook to trigger thumbnail generation.
https://github.com/darron1217/strapi-plugin-video-thumbnail/blob/dd06ae781293eb2489073349254176a39f28915a/config/functions/bootstrap.js#L1-L25

**Comment by darron1217** [comment]
Anyway this issue seems solved.
If you have another issue, feel free to create one :)
